#!/bin/bash

currentbranch=$(git branch | grep \* | cut -d ' ' -f2)
current_commit_msg=$(cat $1)
valid_commit_msg_regex="^(master|develop|((feat|release|hotfix)\/.{1,}):{1} .{1,})"

git log $currentbranch --pretty=format:"%H" --not master > shas.txt

if ! [[ $current_commit_msg =~ $valid_commit_msg_regex ]]
  then
    echo "Your commit message must begin with one of the following:"
    echo "  master: "
    echo "  develop: "
    echo "  feat/description: "
    echo "  release/description: "
    echo "  hotfix/description: "
    echo " "
    exit 1
fi

for i in $(cat ./shas.txt);
  do
    gitmessage=$(git log --format=%B -n 1 "$i" | grep '\S')

    if ! [[ $gitmessage =~ $valid_commit_msg_regex ]]
      then
        echo $gitmessage
        echo "Your commit message must begin with one of the following:"
        echo "  master: "
        echo "  develop: "
        echo "  feat/description: "
        echo "  release/description: "
        echo "  hotfix/description: "
        echo " "
        echo "The commit message with sha: '$i' failed "
        rm shas.txt
        exit 1
    fi
  done

rm shas.txt
exit 0
