#!/bin/sh
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^(master|develop|(feat|release|hotfix)\/[a-z0-9._-]+)$"
message="Branch names in this project must adhere to this contract: $valid_branch_regex."

echo "$(pwd)/src/**/*.{clj,cljs,cljc,edn}"

if [[ $local_branch =~ $valid_branch_regex ]]
then
  echo " "
  exit 0
else
  echo "$message"
  echo " "
  exit 1
fi

echo "$(pwd)/src/**/*.{clj,cljs,cljc,edn}"

if zprint-clj -i "$(pwd)/src/**/*.{clj,cljs,cljc,edn}" -o "$(pwd)"
then
  git add .
  echo " "
  exit 0
else
  echo "Failed to format the Clojure code"
  echo " "
  exit 1
fi

if yarn lint:js
then
  echo " "
  exit 0
else
  echo "Failed to format the Javascript code"
  echo " "
  exit 1
fi
