#!/usr/bin/env node
const childProcessExec = require("child_process").exec;
const util = require("util");

const exec = util.promisify(childProcessExec);

(async () => {
    const localBranch = await exec("git rev-parse --abbrev-ref HEAD");
    const validBranchRegex = new RegExp("^(master|develop|(feat|release|hotfix)\/[a-z0-9._-]+)$", "u");

    if (!validBranchRegex.test(localBranch.stdout.trim())) {
        const message = `Branch names in this project must adhere to this contract: ${validBranchRegex}.`;
        console.log(message);

        process.exit(1);
    }
})();
