#!/usr/bin/env node
const childProcessExec = require("child_process").exec;
const util = require("util");

const exec = util.promisify(childProcessExec);

(async () => {
    const localBranch = await exec("git rev-parse --abbrev-ref HEAD");
    const validBranchRegex = new RegExp("^(master|develop|(feat|release|hotfix)\/[a-z0-9._-]+)$", "u");
    const message = `Branch names in this project must adhere to this contract: ${validBranchRegex}.`;

    if (validBranchRegex.test(localBranch.stdout.trim())) {
        console.log("\n");
        process.exit(0);
    } else {
        console.log(message);
        process.exit(1);
    }
})();

//
// if [[$local_branch = ~$valid_branch_regex]]
//     then
// echo
// " "
// exit
// 0
// else
// echo
// "$message"
// echo
// " "
// exit
// 1
// fi
//
// pwd
//
// echo
// "$(pwd)/src/**/*.cljs"
//
// #if(zprint - clj - i
// "$(pwd)/src/**/*.cljs"
// )
// #then
// #  git
// add.
//     #echo
// " "
// #  exit
// 0
// #else
// #  echo
// "Failed to format the Clojure code"
// #  echo
// " "
// #  exit
// 1
// #fi
// #
// #if
// yarn
// lint:js
// #then
// #  echo
// " "
// #  exit
// 0
// #else
// #  echo
// "Failed to format the Javascript code"
// #  echo
// " "
// #  exit
// 1
// #fi
