name: Build workflow
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/demo-image .
      - name: Publish
        run: gcloud beta run deploy demo-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/demo-image --region us-central1 --platform managed
