name: Code quality workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: docker run -v $PWD/src:/src $PWD/.github:/.github --rm borkdude/clj-kondo clj-kondo --lint src .github