name: Code quality workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: docker run -v $PWD/.github:/.github --rm borkdude/babashka bb -f ./.github/common-scripts/lint-code.clj