name: Code quality workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clj-kondo
        run: |
          curl -sLO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo
          chmod +x install-clj-kondo
          ./install-clj-kondo
      - name: Code quality check
        run: |
          docker build -t app -f /home/runner/work/purechat/purechat/./.github/actions/code-quality-check/Dockerfile .
          docker run app