name: Code quality workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Code quality check
        run: |
          docker build -t app -f /home/runner/work/purechat/purechat/./.github/actions/code-quality-check/Dockerfile .
          docker run app