name: Push workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Lint with clj-kondo
        run: bb -f ./.github/common-scripts/lint-code.clj
      - name: Lint with kibit
        run: bb -f ./.github/common-scripts/kibit-lint.clj

  run-unit-tests:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: bb -f ./.github/common-scripts/run-units.clj