name: Code quality workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get lint-code.clj and kibit-lint.clj code
        id: code_content
        run: |
          echo "::set-output name=lint_code::$(cat ./.github/common-scripts/lint-code.clj)"
          echo "::set-output name=kibit_lint::$(cat ./.github/common-scripts/kibit-lint.clj)"
      - name: Lint the code
        run: echo ${{ steps.code_content.outputs.lint_code }} ${{ steps.code_content.outputs.kibit_lint }}