name: Push workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Validate branch name
        run: bb -f ./.github/common-scripts/validate-branch-name.clj
      - name: Lint with clj-kondo
        run: bb -f ./.github/common-scripts/lint-code.clj
      - name: Lint with kibit
        run: bb -f ./.github/common-scripts/kibit-lint.clj