name: Code quality workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get lint-code.clj and kibit-lint.clj code
        id: code_content
        run: |
          echo "::set-output name=lint_code::$(cat ./.github/common-scripts/lint-code.clj | tr -d '\n')"
          echo "::set-output name=kibit_lint::$(cat ./.github/common-scripts/kibit-lint.clj | tr -d '\n')"
      - name: Lint the code
        uses: ./.github/actions/code-quality-check
        with:
          lint-code-file-content:  ${{steps.code_content.outputs.lint_code}}
          kibit-lint-file-content: ${{steps.code_content.outputs.kibit_lint}}
