name: Develop PR workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  pr-check:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Get title regex
        id: title_regex
      - name: PR check
        run: bb -f ./.github/common-scripts/pr-check.clj <<< "^(master|develop|((feat|release|hotfix)\/[a-z0-9._-]+)){{':'}} [\d\D]+$" ${{github.event.pull_request.head.ref}} ${{github.event.pull_request.title}}  ${{github.event.pull_request.body}}