name: Develop PR workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  pr-check:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Get PR description
        id: pr_description
        run: echo ::set-output name=pr_description::github.event.pull_request.body
      - name: PR check
        run: bb -f ./.github/common-scripts/pr-check.clj '^(master|develop|((feat|release|hotfix)\/[a-z0-9._-]+))$' ${{github.event.pull_request.head.ref}} ${{github.event.pull_request.title}} ${{steps.pr_description.outputs.pr_description}}