name: PR review for the develop branch
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
jobs:
  review-pr-naming:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hello world action step
        uses: ./.github/actions/validate-pr
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
