name: Release PR workflow
on:
  pull_request:
    branches:
      - 'feat/**'
jobs:
  pr-check:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v1
      - name: PR check
        run: bb -f ./.github/common-scripts/pr-check.clj '^(develop|(feat\/[a-z0-9._-]+))$' ${{github.event.pull_request.head.ref}} ${{github.event.pull_request.title}} ${{github.event.pull_request.body}}