name: Release PR workflow
on:
  pull_request:
    branches:
      - 'hotfix/**'
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: PR check
        uses: ./.github/actions/pr-check
        with:
          title-regex: '^(master|(hotfix\/[a-z0-9._-]+)): [\d\D]+$'
          ref-name: ${{github.event.pull_request.head.ref}}
          title: ${{github.event.pull_request.title}}
          description: ${{github.event.pull_request.body}}