name: Release PR workflow
on:
  pull_request:
    branches:
      - master
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: PR check
        uses: ./.github/actions/pr-check
        with:
          title-regex: '^(master|((release|hotfix)\/[a-z0-9._-]+)): [\d\D]+$'
          ref-name: ${{github.event.pull_request.head.ref}}
          title: ${{github.event.pull_request.title}}
          description: ${{github.event.pull_request.body}}

  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get package.json diff
        id: get_package_json_diff
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          echo "::set-output name=PACKAGE_JSON_DIFF::$(git diff origin/master:package.json HEAD:package.json | tr -d '\n')"
      - name: Check package.json version incrementation
        uses: ./.github/actions/release-check
        with:
          package-json-diff: ${{steps.get_package_json_diff.outputs.PACKAGE_JSON_DIFF}}