name: Push workflow
on:
  push:
jobs:
  code-quality-check:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Lint with clj-kondo
        run: bb -f ./.github/common-scripts/lint-code.clj
      - name: Lint with kibit
        run: bb -f ./.github/common-scripts/kibit-lint.clj

  run-unit-tests:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: bb -f ./.github/common-scripts/run-units.clj

  build-and-publish:
    runs-on: ubuntu-latest
    needs: [code-quality-check, run-unit-tests]
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '296.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo "$GITHUB_REF" | sed -e 's/[\/|.]/-/g')"
        id: extract_branch
      - name: Build
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ steps.extract_branch.outputs.branch }} .
      - name: Publish
        run: gcloud run deploy ${{ steps.extract_branch.outputs.branch }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ steps.extract_branch.outputs.branch }} --quiet --region us-central1 --platform managed
